Raise OSError instead of print error when config file not found (#334)
```bash
[tav@myriad repo]$ wpiformat
Traceback (most recent call last):
  File "/home/tav/frc/wpilib/styleguide/wpiformat/wpiformat/config.py", line 39, in read_file
    with open(directory + os.sep + filename, "r") as file_contents:
         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/repo/.styleguide'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tav/.local/bin/wpiformat", line 7, in <module>
    sys.exit(main())
             ~~~~^^
  File "/home/tav/frc/wpilib/styleguide/wpiformat/wpiformat/__init__.py", line 480, in main
    config_file = Config(os.path.dirname(name), ".styleguide")
  File "/home/tav/frc/wpilib/styleguide/wpiformat/wpiformat/config.py", line 15, in __init__
    self.__config_dict = self.__parse_config_file(directory, filename)
                         ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/home/tav/frc/wpilib/styleguide/wpiformat/wpiformat/config.py", line 183, in __parse_config_file
    self.filename, lines = self.read_file(directory, filename)
                           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/home/tav/frc/wpilib/styleguide/wpiformat/wpiformat/config.py", line 48, in read_file
    raise OSError(
        f"config file '{filename}' not found in '{directory}'"
    ) from e
OSError: config file '.styleguide' not found in '/tmp/repo'
```